### ISSUE TITLE
Configuration xsd version update after release

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast-docker#104]
Hi Team, I was around, enterprise dockerfile adds `hazelcast.xml` that have version `3.9 xsd`, I think,  we may update it after releases or consider removing it.

**Comment by leszko** [comment]
We should do #116 instead and change XML to YAML. For `hazelcast-oss` we can actually remove the whole `hazelcast.xml`, because Management Center URL will be removed in `4.0`.
