### ISSUE TITLE
ConnectionManager JMX metrics are missing in 3.12

### ISSUE THREAD

**Issue by maxout123** [hazelcast/hazelcast-docker#114]
After upgrade of Hazelcast from 3.11.2 to 3.12, JMX metrics for ConnectionManager are not available in prometheus exporter anymore. All other metrics are there.

I may be wrong, but it seems that ConnectionManager was replaced by NetworkingService in 3.12. But there are no any metrics for NetworkingService in jmx prometheus exporter also.

If I connect to JMX directly, metrics for NetworkingService are there. But prometheus exporter metrics doesn't contain them.

**Comment by leszko** [comment]
@maxout123 You can use your own `jmx_agent_config.yaml`. Or feel free to modify [hazelcast-oss/jmx_agent_config.yaml](https://github.com/hazelcast/hazelcast-docker/blob/master/hazelcast-oss/jmx_agent_config.yaml) and send a PR. Thanks!

**Comment by maxout123** [comment]
If I ever could..

I see that jmx_agent_config.yaml contains no any hardcoded bean and metric names, so I suppose that it exports everything it sees in JMX.

As an example, in JMX i can see two metrics:
1. jmx["com.hazelcast:instance={$INSTANCE_NAME},name={$INSTANCE_NAME},type=HazelcastInstance.NetworkingService",activeConnectionCount]
2. jmx["com.hazelcast:instance={$INSTANCE_NAME},name={$INSTANCE_NAME},type=HazelcastInstance.PartitionServiceMBean",activePartitionCount]

But prometheus exporter (the same instance, of course) exports second metric, but first is absent. No any metric of NetworkingService bean is exported.

I can't to figure out, what should I do in jmx_agent_config.yaml to fix that.

**Comment by leszko** [comment]
@maxout123 Did you specify the option "-Dhazelcast.jmx=true" as described [here](https://github.com/hazelcast/hazelcast-docker#prometheus)?

**Comment by maxout123** [comment]
Sure, I see all metrics, JVM ones and Hazelcast ones. There are simply no ConnectionManager and NetworkingService metrics.

I've created gist from exporter metrics:
https://gist.github.com/maxout123/c36bb0456e152948cd3bd70f924ad33d
This is all metrics exported, no redactions.

ENV of the Hazelcast statefulset:
       env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PROMETHEUS_PORT
          value: "8080"
        - name: MANCENTER_URL
          value: "http://hazelcast-mancenter:8080/hazelcast-mancenter"
        - name: JMX_PORT
          value: "9999"
        - name: SERVICE_NAME
          value: "hazelcast"
        - name: JAVA_OPTS
          value: >-
            -Dcom.sun.management.jmxremote.rmi.port=$(JMX_PORT)
            -Djava.rmi.server.hostname=$(HOSTNAME).$(SERVICE_NAME).$(NAMESPACE)
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.local.only=false
            -Dhazelcast.jmx=true
            -Dcom.sun.management.jmxremote.port=$(JMX_PORT)
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false
            -Dhazelcast.rest.enabled=true
            -Dhazelcast.config=/data/hazelcast/hazelcast.xml
            -DserviceName=$(SERVICE_NAME)
            -Dnamespace=$(NAMESPACE)
            -Dhazelcast.shutdownhook.policy=GRACEFUL
            -Dhazelcast.graceful.shutdown.max.wait=60
            -XX:+UnlockExperimentalVMOptions
            -XX:+UseCGroupMemoryLimitForHeap
            -XX:MaxRAMFraction=2
            -XshowSettings:vm

**Comment by mesutcelik** [comment]
I created an issue based on this discussion. 
https://github.com/hazelcast/hazelcast/issues/15681

**Comment by mdumandag** [comment]
Hi @maxout123 

I sent a fix to the Hazelcast side. Your problem should be solved when the Hazelcast IMDG 3.12.5 is released. For now, I tested the metrics against the 3.12.5 snapshot jar and saw that they are correctly collected after the fix. See https://gist.github.com/mdumandag/2ba181bca016bd699ce4a9e414c5f35d

**Comment by mesutcelik** [comment]
Thanks @mdumandag !

I am closing this issue. Please feel free to reopen if you see any problem.
