### ISSUE TITLE
Jmx exporter is not showing hazelcast related information

### ISSUE THREAD

**Issue by mukul4u2005** [hazelcast/hazelcast-docker#119]
Hi 

I am using default jmx-exporter (https://github.com/hazelcast/hazelcast-docker/blob/master/hazelcast-oss/jmx_agent_config.yaml) with -Dhazelcast.jmx=true , its just showing jvm jmx information not hazelcast related one . I am running this exporter as java agent on openshift . any idea whats wrong here: 

Vm argument: 

-javaagent:/jmx_prometheus_javaagent.jar=8080:/tmp/config/config.yml -DserviceName=myhzapp-os-test -Dhazelcast.jmx=true

logs:

Members {size:1, ver:1} [
--
  | Member [192.168.9.253]:5701 - ea31f018-8636-4343-9004-d2ff51acfb30 this
  | ]
  |  
  | Jun 25 2019 16:10:36:471 UTC - [main] - INFO - com.hazelcast.internal.jmx.ManagementService.<init> - [192.168.9.253]:5701 [myhzapp-os-test] [3.12] Hazelcast JMX agent enabled.
  | Jun 25 2019 16:10:36:476 UTC - [hz._hzInstance_1_myhzapp-os-test.HealthMonitor] - INFO - com.hazelcast.internal.diagnostics.HealthMonitor$HealthMonitorThread.run - [192.168.9.253]:5701 [myhzapp-os-test] [3.12] processors=1, physical.memory.total=125.8G, physical.memory.free=18.4G, swap.space.total=0, swap.space.free=0, heap.memory.used=11.7M, heap.memory.free=8.8M, heap.memory.total=20.4M, heap.memory.max=247.5M, heap.memory.used/total=57.09%, heap.memory.used/max=4.71%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, load.process=2.22%, load.system=48.89%, load.systemAverage=21.55, thread.count=38, thread.peakCount=38, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0

Getting exporter output as:

sh-4.2$ curl localhost:8080/metrics
# HELP jvm_classes_loaded The number of classes that are currently loaded in the JVM
# TYPE jvm_classes_loaded gauge
jvm_classes_loaded 7410.0
# HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
# TYPE jvm_classes_loaded_total counter
jvm_classes_loaded_total 7410.0
# HELP jvm_classes_unloaded_total The total number of classes that have been unloaded since the JVM has started execution
# TYPE jvm_classes_unloaded_total counter
jvm_classes_unloaded_total 0.0
# HELP jvm_threads_current Current thread count of a JVM
# TYPE jvm_threads_current gauge
jvm_threads_current 48.0
# HELP jvm_threads_daemon Daemon thread count of a JVM
# TYPE jvm_threads_daemon gauge
jvm_threads_daemon 14.0
# HELP jvm_threads_peak Peak thread count of a JVM
# TYPE jvm_threads_peak gauge
jvm_threads_peak 48.0
# HELP jvm_threads_started_total Started thread count of a JVM
# TYPE jvm_threads_started_total counter
jvm_threads_started_total 54.0
# HELP jvm_threads_deadlocked Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers
# TYPE jvm_threads_deadlocked gauge
jvm_threads_deadlocked 0.0
# HELP jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors
# TYPE jvm_threads_deadlocked_monitor gauge
jvm_threads_deadlocked_monitor 0.0
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
# HELP jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE jvm_gc_collection_seconds summary
jvm_gc_collection_seconds_count{gc="Copy",} 53.0
jvm_gc_collection_seconds_sum{gc="Copy",} 0.148
jvm_gc_collection_seconds_count{gc="MarkSweepCompact",} 3.0
jvm_gc_collection_seconds_sum{gc="MarkSweepCompact",} 0.113
# HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds.
# TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 0.003691473
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 0.0
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 7.96
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.561479017402E9
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 60.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1048576.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 5.356670976E9
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.49266432E8
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 2.1103856E7
jvm_memory_bytes_used{area="nonheap",} 4.4948176E7
# HELP jvm_memory_bytes_committed Committed (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_committed gauge
jvm_memory_bytes_committed{area="heap",} 3.3841152E7
jvm_memory_bytes_committed{area="nonheap",} 4.58752E7
# HELP jvm_memory_bytes_max Max (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_max gauge
jvm_memory_bytes_max{area="heap",} 2.5952256E8
jvm_memory_bytes_max{area="nonheap",} -1.0
# HELP jvm_memory_bytes_init Initial bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_init gauge
jvm_memory_bytes_init{area="heap",} 1.6777216E7
jvm_memory_bytes_init{area="nonheap",} 2555904.0
# HELP jvm_memory_pool_bytes_used Used bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_used gauge
jvm_memory_pool_bytes_used{pool="Code Cache",} 6745216.0
jvm_memory_pool_bytes_used{pool="Metaspace",} 3.3651552E7
jvm_memory_pool_bytes_used{pool="Compressed Class Space",} 4551408.0
jvm_memory_pool_bytes_used{pool="Eden Space",} 4680984.0
jvm_memory_pool_bytes_used{pool="Survivor Space",} 78008.0
jvm_memory_pool_bytes_used{pool="Tenured Gen",} 1.6344864E7
# HELP jvm_memory_pool_bytes_committed Committed bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_committed gauge
jvm_memory_pool_bytes_committed{pool="Code Cache",} 6815744.0
jvm_memory_pool_bytes_committed{pool="Metaspace",} 3.4340864E7
jvm_memory_pool_bytes_committed{pool="Compressed Class Space",} 4718592.0
jvm_memory_pool_bytes_committed{pool="Eden Space",} 9437184.0
jvm_memory_pool_bytes_committed{pool="Survivor Space",} 1179648.0
jvm_memory_pool_bytes_committed{pool="Tenured Gen",} 2.322432E7
# HELP jvm_memory_pool_bytes_max Max bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_max gauge
jvm_memory_pool_bytes_max{pool="Code Cache",} 2.5165824E8
jvm_memory_pool_bytes_max{pool="Metaspace",} -1.0
jvm_memory_pool_bytes_max{pool="Compressed Class Space",} 1.073741824E9
jvm_memory_pool_bytes_max{pool="Eden Space",} 7.1630848E7
jvm_memory_pool_bytes_max{pool="Survivor Space",} 8912896.0
jvm_memory_pool_bytes_max{pool="Tenured Gen",} 1.78978816E8
# HELP jvm_memory_pool_bytes_init Initial bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_init gauge
jvm_memory_pool_bytes_init{pool="Code Cache",} 2555904.0
jvm_memory_pool_bytes_init{pool="Metaspace",} 0.0
jvm_memory_pool_bytes_init{pool="Compressed Class Space",} 0.0
jvm_memory_pool_bytes_init{pool="Eden Space",} 4521984.0
jvm_memory_pool_bytes_init{pool="Survivor Space",} 524288.0
jvm_memory_pool_bytes_init{pool="Tenured Gen",} 1.1206656E7
# HELP jvm_buffer_pool_used_bytes Used bytes of a given JVM buffer pool.
# TYPE jvm_buffer_pool_used_bytes gauge
jvm_buffer_pool_used_bytes{pool="direct",} 434308.0
jvm_buffer_pool_used_bytes{pool="mapped",} 0.0
# HELP jvm_buffer_pool_capacity_bytes Bytes capacity of a given JVM buffer pool.
# TYPE jvm_buffer_pool_capacity_bytes gauge
jvm_buffer_pool_capacity_bytes{pool="direct",} 434308.0
jvm_buffer_pool_capacity_bytes{pool="mapped",} 0.0
# HELP jvm_buffer_pool_used_buffers Used buffers of a given JVM buffer pool.
# TYPE jvm_buffer_pool_used_buffers gauge
jvm_buffer_pool_used_buffers{pool="direct",} 11.0
jvm_buffer_pool_used_buffers{pool="mapped",} 0.0
# HELP jvm_info JVM version info
# TYPE jvm_info gauge
jvm_info{version="1.8.0_201-b10",vendor="Azul Systems, Inc.",runtime="OpenJDK Runtime Environment",} 1.0
# HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0

**Comment by leszko** [comment]
May be related to #114

**Comment by mukul4u2005** [comment]
But I am doing enable -Dhazelcast.jmx=true , it’s just pulling Jvm related metrics not hazelcast. 

I can check hazelcast related beans in jconsol but jvm exporter not pulling that information.

**Comment by mukul4u2005** [comment]
ok i got it fix , I set instance name explicitly not generated one , then its fixed and picked all jmx details.

Thanks for replying , One question or suggestion from your side :

JMX exporter does not return all information like member ip address , Do we need to write custom exporter to get these kind of details?

**Comment by mukul4u2005** [comment]
Could you please reply above comment and we can close this issue ?

**Comment by leszko** [comment]
Yeah, you can either write your own prometheus agent configuration or send a PR to this repo and update the existing configuration to return all information.

**Comment by mesutcelik** [comment]
It is good to see that worked for you @mukul4u2005 !

**Comment by seckinsq** [comment]
To state the problem for other users who find this thread : If you use default jmx_agent_config.yaml but with a hazelcast group name that has "-" then hazelcast jmx metrics are not scraped.
This does not show hazelcast related metrics :
`-Dhazelcast.group.name="dev-tr"`
This works :
`-Dhazelcast.group.name="devtr"`
