### ISSUE TITLE
Main class in hazelcast-all is change

### ISSUE THREAD

**Issue by ByJacob** [hazelcast/hazelcast-docker#122]
Actual Main class in hazelcast server have name com.hazelcast.core.server.StartServer. Docker try run class com.hazelcast.core.server.HazelcastMemberStarter, bit it don't exist

**Comment by Holmistr** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast-docker/pull/121 . Now going to rebuild the Docker image, I'll let you know.

Thank you for reporting the issue!

**Comment by Holmistr** [comment]
Docker image rebuilt, everything is fixed. Thank you very much for your contribution.
