### ISSUE TITLE
Consider including logging libraries  (eg. log4j, log4j2, logback)

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-docker#129]
Related to the issue created in the Helm Chart repository: https://github.com/hazelcast/charts/issues/53

**Comment by jerrinot** [comment]
I think it's alright to pick any logging framework, but JUL. 
Hazelcat Jet uses log4j2, that sounds like a good choice. 

Compare `docker run -p 5701:5701 hazelcast/hazelcast-jet`
![image](https://user-images.githubusercontent.com/158619/88180816-36e8a680-cc2e-11ea-91c9-8aa6ee367eb9.png)
vs.
`docker run -p 5701:5701 hazelcast/hazelcast`
![image](https://user-images.githubusercontent.com/158619/88180905-567fcf00-cc2e-11ea-9e6b-178fcea0d642.png)
