### ISSUE TITLE
Fix description in docker hub

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-docker#131]
The "short" description for hazelcast/hazelcast-jet currently says "hazelcast-jet build", not sure where this is coming from. Also needs review for the other images.

For hazelcast/hazelcast-jet-management-center the variable should be called `$HAZELCAST_JET_MANAGEMENT_CENTER_VERSION` instead.

**Comment by cangencer** [comment]
also hazelcast/hazelcast-jet text refers to Hazelcast Jet Enterprise version

**Comment by gurbuzali** [comment]
I guess this issues belongs to here https://github.com/hazelcast/hazelcast-jet-docker

**Comment by leszko** [comment]
> I guess this issues belongs to here https://github.com/hazelcast/hazelcast-jet-docker

@cangencer can I close this issue then?

**Comment by cangencer** [comment]
Yes sorry, I meant to open this in the other repository, but we've fixed it now.
