### ISSUE TITLE
[Documentation] The directions to run management center does not work.

### ISSUE THREAD

**Issue by SiddhantJ19** [hazelcast/hazelcast-docker#139]
[Current Document](https://github.com/hazelcast/hazelcast-docker#management-center-hello-world) to help getting started with hazelcast docker image and management center does not work. It should be updated like as suggested by @mesutcelik  [here](https://gitter.im/hazelcast/hazelcast#)

```
// running the management center container
$ docker run -d -p 8080:8080 --name management-center hazelcast/management-center:$MANAGEMENT_CENTER_VERSION

$ MANCENTER_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' management-center)

// running the hazelcast container
$ docker run -d -e MANCENTER_URL="http://${MANCENTER_IP}:8080/hazelcast-mancenter" hazelcast/hazelcast:$HAZELCAST_VERSION 
```

Or even provide a sample docker-compose file to do the same.

**Comment by SiddhantJ19** [comment]
I've some idea for the docker compose file. How do I make a pr?

**Comment by mesutcelik** [comment]
@SiddhantJ19 Thanks for the issue. I updated your comment to simplify. 

I would create a docker-compose folder with its own README a sample docker-compose.yaml. cc: @leszko

**Comment by mesutcelik** [comment]
The other option to use is to create a docker network and use container names as dns names. 

```
$ docker network create myNetwork
$ docker run -d -p 8080:8080 --net mynetwork --name management-center hazelcast/management-center:3.12.8
$ docker run -d -e MANCENTER_URL="http://management-center:8080/hazelcast-mancenter" --net myNetwork hazelcast/hazelcast:3.12.6
```

**Comment by leszko** [comment]
I think the current description is fine with the Hazelcast 4.0+. @SiddhantJ19 could you point out what does not work for you?

For older versions (3.12.x), you can use [this description](https://github.com/hazelcast/hazelcast-docker/tree/3.12.z).

@mesutcelik wrt docker compose, hmm, I don't know, have you seen it somewhere? I would weight how helpful it is vs how much maintenance effort it brings.

**Comment by SiddhantJ19** [comment]
@leszko I wanted to run the man center as a docker container as well. Maybe you could add the link for documentation for versions 3.12.x in the doc itself. Also having the docker-compose option might help in getting up and running more quickly.

**Comment by ldziedziul** [comment]
Docker compose configuration for MC can be found here: https://docs.hazelcast.com/management-center/5.3/getting-started/get-started#step-1-run-hazelcast-from-a-docker-container
