### ISSUE TITLE
removal of stop scripts from docker images

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-docker#16]
Instead of maintaining PID based stop script, we should rely on docker stop [docker stop](https://docs.docker.com/engine/reference/commandline/stop/)

see https://github.com/hazelcast/hazelcast-docker/pull/15

**Comment by mesutcelik** [comment]
I think we will keep `stop.sh` in the repo in case someone wants to stop hazelcast via script before stopping Docker container. In normal conditions, we do not need stop.sh

**Comment by ps-jay** [comment]
For anyone following this issue, the scripts have now been removed as part of #66.
