### ISSUE TITLE
Please allow user code deployment to be enabled from environment config

### ISSUE THREAD

**Issue by rvaidya** [hazelcast/hazelcast-docker#161]
It would be useful to have user code deployment be enabled from docker environment config, instead of having to do this in file config or having to extend the docker image.

https://docs.hazelcast.org/docs/latest/manual/html-single/#configuring-user-code-deployment

**Comment by rvaidya** [comment]
It looks like hazelcast itself would need to expose this as a system property, which it does not currently do

**Comment by leszko** [comment]
@rvaidya starting from Hazelcast 4.1, you can configure all Hazelcast options using env variables (or JVM properties). Please check [Hazelcast Reference Manual: Overriding Configuration](https://docs.hazelcast.org/docs/4.1-BETA-1/manual/html-single/#overriding-configuration).

**Comment by rvaidya** [comment]
Thanks, this does work:

docker run -e HZ_USERCODEDEPLOYMENT_ENABLED=true -p 5701:5701 hazelcast/hazelcast:4.1-BETA-1
