### ISSUE TITLE
Potential performance regression in 4.0.2 image

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-docker#165]
`hazelcast/hazelcast:4.0.2` is around 30% slower than a single member .jar running with OpenJDK 11.0.8+10.

See https://github.com/hazelcast/hazelcast-nodejs-client/issues/559#issuecomment-696116277

**Comment by pveentjer** [comment]
Is this specific to 4.0.2 or with 4.0 it also is problematic?

**Comment by puzpuzpuz** [comment]
@pveentjer I only tested with 4.0.2. Not sure about 4.0 or other tags.

**Comment by puzpuzpuz** [comment]
> And what are the differences apart from Hazelcast version with the previous Docker images? Perhaps a different JRE is used?

Yes, 4.0.2 uses Java 11, while in 3.12.9 it's Java 8.

**Comment by pveentjer** [comment]
One big difference the GC algorithm being used. Java 8 by default uses Parallel, and 9+ use G1.

Could you do a run with your 4.0.1 image and add `-XX:+UseParallelGC`

**Comment by puzpuzpuz** [comment]
> One big difference is the GC algorithm being used. Java 8 by default uses Parallel, and 9+ use G1.
> 
> Could you do a run with your 4.0.2 image and add `-XX:+UseParallelGC`

Nope, that's not the case. See `-XX:+UseParallelGC` here: https://github.com/hazelcast/hazelcast-docker/blob/v4.0.2/hazelcast-oss/Dockerfile#L23

Also, when I was running a member directly with OpenJDK 11 I was using the default GC (which is G1) and it played no role. The benchmark scenario does not assume a significant allocation rate, so any GC will do fine.

**Comment by pveentjer** [comment]
Could you do a run with just 3.12.x but using the 4.0.2 'image'? So that the only change is the HZ version.

**Comment by Holmistr** [comment]
Or perhaps if you could share the test you're running as well.

**Comment by puzpuzpuz** [comment]
> Or perhaps if you could share the test you're running as well.

@Holmistr it's shared. See the link.

**Comment by puzpuzpuz** [comment]
> Could you do a run with just 3.12.x but using the 4.0.2 'image'? So that the only change is the HZ version.

I can do the experiment and the later analysis once I'm done with upcoming Node.js client releases.

**Comment by pivovarit** [comment]
The Alpine base image is using musl and not glibc. Always wanted to investigate if this had any real impact on our benchmarks

**Comment by puzpuzpuz** [comment]
@pivovarit the 3.12.9 image also uses Alpine (and thus, musl), right? I saw no problems with the images, so I'm not sure if that's the case.

**Comment by pivovarit** [comment]
Just dropping an idea to investigate. For sure these are two different versions of Alpine (3.8 vs 3.11)

**Comment by puzpuzpuz** [comment]
> Could you do a run with just 3.12.x but using the 4.0.2 'image'? So that the only change is the HZ version.

@pveentjer I did the experiment. The changes are here https://github.com/puzpuzpuz/hazelcast-docker/commit/9d2e329500dec6d675c70c4e301ffa62ab240d50

Benchmark scenario: `map.get()` for 1KB value, 1M ops with 128 concurrently running ops, 15 runs for each: Docker container (OpenJDK 1.8.0_222) and `java -jar` (OpenJDK 11.0.8+10).

Result with Docker container:
```
Ops/s: 101147.33668460751
Ops/s: 109209.02812225324
Ops/s: 136390.78802498503
Ops/s: 98171.1602665734
Ops/s: 95856.40123380409
Ops/s: 178278.23184115323
Ops/s: 97134.0141615621
Ops/s: 103434.09624231629
Ops/s: 99054.49553975328
Ops/s: 95806.50272743402
Ops/s: 178318.61267744156
Ops/s: 95781.84755518513
Ops/s: 101475.60127609217
Ops/s: 98184.65764962722
Ops/s: 96882.37636951778
```

Result with `java -jar`:
```
Ops/s: 206861.99652612675
Ops/s: 167495.45012176875
Ops/s: 167814.4098568342
Ops/s: 169028.91494215242
Ops/s: 164433.49485237055
Ops/s: 166098.9604072363
Ops/s: 162761.52781079468
Ops/s: 178910.04954556897
Ops/s: 160564.47607905947
Ops/s: 160746.76561155624
Ops/s: 161035.3051753087
Ops/s: 196544.90414971721
Ops/s: 158793.61618793444
Ops/s: 156182.37561812793
Ops/s: 159988.59353003022
```

So, the jitter is still there. I'll try to check other potential differences.

**Comment by puzpuzpuz** [comment]
I would appreciate if someone could try to reproduce the problem locally. This would allow us to understand whether it's something local to my machine or not.

**Comment by puzpuzpuz** [comment]
As @frant-hartm pointed, the regression could be explained by port mapping (i.e. Docker's NAT). See [this comparison](https://stackoverflow.com/questions/21889053/what-is-the-runtime-performance-cost-of-a-docker-container/26149994#26149994). I'm going to repeat measurements for 4.0.2 with host network next week and report my findings here.

**Comment by puzpuzpuz** [comment]
Did the experiment today and here is the result.

Node.js client - latest `master` (https://github.com/hazelcast/hazelcast-nodejs-client/commit/39ea86f71f403c4cdc5d408802707232105f9773)

`new` stands for `docker run --net=host hazelcast/hazelcast:4.0.2`
`old` stands for `docker run -p 5701:5701 hazelcast/hazelcast:4.0.2`

```
$ cat compare-docker-networks.csv | Rscript benchmark/compare.R
                                             confidence improvement accuracy (*)    (**)   (***)
 benchmark/Benchmark.js get t=1M s=1KB c=128         **     26.78 %      ±16.73% ±22.80% ±30.81%

Be aware that when doing many comparisons the risk of a false-positive
result increases. In this case there are 1 comparisons, you can thus
expect the following amount of false-positive results:
  0.05 false positives, when considering a   5% risk acceptance (*, **, ***),
  0.01 false positives, when considering a   1% risk acceptance (**, ***),
  0.00 false positives, when considering a 0.1% risk acceptance (***)
```

![compare-docker-networks-plot](https://user-images.githubusercontent.com/37772591/98909854-6e2bdd80-24d3-11eb-829a-a43602fea837.png)

Both scenarios include some outliers which is interesting. Another thing to notice is that the confidence level is not very high, but things could change with more runs (I only did 15 runs for each scenario).

Nevertheless, it looks like the result can be explained by the latency introduced by Docker's NAT, so I'm going to close this issue. Many thanks to @frant-hartm who pointed at the right direction!
