### ISSUE TITLE
Backport vulnerability scan for 3.12.z branch

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-docker#176]
We should make the 3.12.z Docker images vulnerability free, it means we need to backport the changes we did for the master branch (for Hazelcast 4.x):
- Create GH Action: "Vulnerability Scan 3.12.x image"
- If there are any failures in Eureka transitive dependencies, then we need to update versions of those

**Comment by enozcan** [comment]
> If there are any failures in Eureka transitive dependencies, then we need to update versions of those

I believe this should be indicated by another issue as this one is named `Backport vulnerability scan ...`. Hence closing this. Please reopen or create another issue if the statement above is still the case.

Closed via #183 and #184.
