### ISSUE TITLE
Image is not using latest JDK11 version

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-docker#195]
Docker image is using JDK 11.0.5, latest is 11.0.9

**Comment by pivovarit** [comment]
Just one note, if we switched the base image to `adoptopenjdk/openjdk11:jdk-11.0.9_11-alpine`, we could leverage Dependabot and simplify our _Dockerfile_.

**Comment by ldziedziul** [comment]
Done within https://github.com/hazelcast/hazelcast-docker/pull/576
