### ISSUE TITLE
Use JDK default GC by default

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-docker#197]
Docker image defaults to ParallelGC. It is old and outdated, and creates stop the world pauses which are undesirable for modern workloads. Use the default GC of the JVM used instead (G1).

**Comment by pivovarit** [comment]
CC @Holmistr 

https://github.com/hazelcast/hazelcast-docker/pull/126#issuecomment-571491821

**Comment by cangencer** [comment]
"parallel GC as default creates the best out of the box experience for most users." -> what is this based on?

**Comment by Holmistr** [comment]
I don't really remember TBH why I said that in particular. For throughput oriented workloads, parallel GC will give you the best performance if you don't run into major GC problems, which e.g. with HD, you probably (hopefully) won't. 
Perhaps this can be reevaluated based on the research Marko did with the GCs.

The decision which GC to use should probably be based on that we should state clearly that we want to optimize for latency or throughput oriented workloads. I don't have a strong opinion here.

**Comment by cangencer** [comment]
@pveentjer could you advise here about which GC should be default?

I would think predictable latency under a variety of workloads is a reasonable default. Thus my vote is for G1 which has come a long way according to the latest work Marko did.

**Comment by mtopolnik** [comment]
We should use the newest JDK (15) and G1 with `-XX:MaxGCPauseMillis=5`. The impact on throughput compared to Parallel is pretty low and the impact on latency is orders of magnitude.

**Comment by leszko** [comment]
I think it's a good idea! Can someone send a PR with the change?

**Comment by pivovarit** [comment]
I will take care of that.

**Comment by leszko** [comment]
Thanks @pivovarit
