### ISSUE TITLE
Does running the hazelcast/management-center require a enterprise license?

### ISSUE THREAD

**Issue by hirro** [hazelcast/hazelcast-docker#2]
As far as I understand it, the image hazelcast/hazelcast can be run for commercial usage (closed source). 

How about the management-center? Can it be used for free?

**Comment by gAmUssA** [comment]
Management Center can be used for free with cluster of 2 nodes only.
Thanks

**Comment by hirro** [comment]
Are there any similar restrictions on the oss-version of Hazelcast?

**Comment by bilalyasar** [comment]
there is no restriction for hazelcast-oss. Also mancenter restriction is not docker special restriction.

**Comment by hirro** [comment]
Thanks! Great image btw!
