### ISSUE TITLE
Document semantic of the `latest` tag

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-docker#206]
https://hub.docker.com/r/hazelcast/hazelcast does not tell what's the meaning of the `latest` snapshot. What version of Hazelcast to expect under this tag? We should be explicit about it.

**Comment by hasancelik** [comment]
I think it should be latest stable(4.1). We will re-evaluate this tag and add new ones during [Snapshot Based IMDG and Enterprise Docker Images](https://hazelcast.atlassian.net/wiki/spaces/PM/pages/2675409251/Snapshot-Based+IMDG+and+Enterprise+Docker+Images) PRD. cc: @mtyazici
