### ISSUE TITLE
Issue installing dockerize for generating config files using templates for 4.1.1

### ISSUE THREAD

**Issue by hsomu** [hazelcast/hazelcast-docker#236]
We are trying to install dockerize for generating config files using templates and this is working till hazelcast-enterprise:4.0, but for 4.1.1 version, we are seeing below error:

Step 23/27 : RUN curl -sL https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | tar zxf - -C /bin/
 ---> Running in 07434baf7064
tar: can't open 'dockerize': Permission denied

Below is a sample Dockerfile content:

FROM hazelcast/hazelcast-enterprise:4.1.1
ADD hazelcast.xml ${HZ_HOME}
RUN curl -sL https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | tar zxf - -C /bin/
ENV JAVA_OPTS -Dhazelcast.config=${HZ_HOME}/hazelcast.xml

Need some help over here, we assume it is because of the base image being is different from 4.0 to 4.1.1

**Comment by hasancelik** [comment]
Hi @hsomu,

There is only OS version of base image change between `4.0` and `4.1.1` image. `4.0` uses `alpine:3.11`, `4.1.1` uses `alpine:3.12.2` :
https://github.com/hazelcast/hazelcast-docker/blob/01a3d5bad5c1684b8d5419f7e7c6d420c1d567ab/hazelcast-enterprise/Dockerfile#L1
https://github.com/hazelcast/hazelcast-docker/blob/8e531f5a8a87c268d95dd3cad9abf6693d70c9e8/hazelcast-enterprise/Dockerfile#L1

We will change base image of enterprise to `ubi-minimal:8.3` with `4.1.2` release, FYI.

When I check `dockerize` repo, I can see another binary for alpine envs. Did you try with that? 
https://github.com/jwilder/dockerize#installation

**Comment by hsomu** [comment]
Hi @hasancelik,

Thanks for the reply. Tried with binary for alpine envs also but seeing the same issue. Mean this is working for 4.0 without any issues for alpine envs without any change.

**Comment by hasancelik** [comment]
@hsomu,

It seems the issue is related folder permissions. `hazelcast` user has only read permission for `/opt/hazelcast` which is default WORKDIR for the container. You can change your directory to `/home/hazelcast` before install the tar.gz.

**Comment by hsomu** [comment]
Thanks for all the help @hasancelik. It helped.

**Comment by hasancelik** [comment]
Glad to hear that 👍
