### ISSUE TITLE
Red Hat Hazelcast Enterprise Image Latest Tag Ambiguity

### ISSUE THREAD

**Issue by mtyazici** [hazelcast/hazelcast-docker#242]
For the Images pushed to the Red Hat registry after a tag creation, we don't have a way of altering the latest tag. New images might always have a latest tag or they might get the latest tag according to their semantic versioning. There is an open case at Red Hat support about this issue. 

Also, we don't want `BETA` versions to have the latest tag. However, as we don't have a way of interfering with the latest tag creation at Red Hat registry using code, we must change them from the portal manually.

**Comment by ldziedziul** [comment]
I think it's fixed now, AFAIK `latest` points now to the latest stable release.
