### ISSUE TITLE
Unrecognized environment variables

### ISSUE THREAD

**Issue by hsomu** [hazelcast/hazelcast-docker#246]
Hi,

While bringing up the haxelcast server, we are seeing following warn:
[ WARN] [main] [c.p.h.i.c.o.ExternalConfigurationOverride]: Unrecognized environment variables configuration entries: [hazelcast.cs.auth.password, hazelcast.graceful.shutdown.max.wait.seconds, hazelcast.max.join.seconds, hazelcast.health.monitoring.level, hazelcast.cs.auth.username]

After analyzing the issue, we came to know that we are passing ENV variables from Dockerfile script where few of the ENV variables are starting with "HZ_" prefix in this case for example as below:
**ENV HZ_GRACEFUL_SHUTDOWN_MAX_WAIT_SECONDS 600** because of which we are seeing Unrecognized environment variable hazelcast.graceful.shutdown.max.wait.seconds.

Are there any naming naming conventions for declaring ENV variables that we should not use "HZ_" or similar.

**Comment by hsomu** [comment]
Thank You @leszko for the quick reply.

**Comment by leszko** [comment]
Closing. Feel free to reopen if needed.
