### ISSUE TITLE
Remove `TLS_ENABLED` env variable from Hazelcast Enterprise image

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-docker#247]
Now that we have [Overriding Configuration](https://docs.hazelcast.com/imdg/latest/configuration/overriding-configuration-settings.html) feature in place, we don't need this parameter.

We can still keep it backward-compatible, but it should be removed from the README and system property.

**Comment by hasancelik** [comment]
@leszko It is already fixed with long-standing https://github.com/hazelcast/hazelcast-docker/pull/213. We can merge it after your approval 👍
