### ISSUE TITLE
java.io.EOFException: Remote socket Closed

### ISSUE THREAD

**Issue by Shub1427** [hazelcast/hazelcast-docker#25]
Getting this Exception when trying to connect **Mancenter via Host** or the **Docker Mancenter** to Docker **Hazelcast:3.5.3**...
```
hazelcast    | Members [1] {
hazelcast    | 	Member [172.19.0.3]:5701 this
hazelcast    | }
hazelcast    | 
hazelcast    | Apr 03, 2017 8:53:05 AM com.hazelcast.core.LifecycleService
hazelcast    | INFO: [172.19.0.3]:5701 [dev] [3.5.3] Address[172.19.0.3]:5701 is STARTED
hazelcast    | Apr 03, 2017 8:53:05 AM com.hazelcast.internal.management.ManagementCenterService
hazelcast    | INFO: [172.19.0.3]:5701 [dev] [3.5.3] Hazelcast will connect to Hazelcast Management Center on address: 
hazelcast    | http://0.0.0.0:7080/mancenter-3.5.2
hazelcast    | Apr 03, 2017 8:53:05 AM com.hazelcast.internal.management.ManagementCenterService
hazelcast    | INFO: [172.19.0.3]:5701 [dev] [3.5.3] Failed to connect to:http://0.0.0.0:7080/mancenter-3.5.2/collector.do
hazelcast    | Apr 03, 2017 8:53:05 AM com.hazelcast.internal.management.ManagementCenterService
hazelcast    | INFO: [172.19.0.3]:5701 [dev] [3.5.3] Failed to pull tasks from management center
hazelcast    | Apr 03, 2017 8:53:05 AM com.hazelcast.partition.InternalPartitionService
hazelcast    | INFO: [172.19.0.3]:5701 [dev] [3.5.3] Initializing cluster partition table first arrangement...
hazelcast    | Apr 03, 2017 8:53:28 AM com.hazelcast.nio.tcp.SocketAcceptor
hazelcast    | INFO: [172.19.0.3]:5701 [dev] [3.5.3] Accepting socket connection from /172.19.0.1:42718
hazelcast    | Apr 03, 2017 8:53:28 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
hazelcast    | INFO: [172.19.0.3]:5701 [dev] [3.5.3] Established socket connection between /172.19.0.3:5701
hazelcast    | Apr 03, 2017 8:53:28 AM com.hazelcast.internal.management.ManagementCenterService
hazelcast    | INFO: [172.19.0.3]:5701 [dev] [3.5.3] Management Center URL has changed. Hazelcast will connect to Management Center on address:
hazelcast    | http://localhost:7080/mancenter-3.5.2
hazelcast    | Apr 03, 2017 8:53:37 AM com.hazelcast.nio.tcp.TcpIpConnection
hazelcast    | INFO: [172.19.0.3]:5701 [dev] [3.5.3] Connection [/172.19.0.1:42718] lost. Reason: java.io.EOFException[Remote socket closed!]
```

Attached Fille contains my hazelcast.xml config file, where I have enabled the Mancenter...

I am providing following ```JAVA_OPTS: "-Xms250M -Xmx250M -Dhazelcast.config=/opt/hazelcast/configFolder/hazelcast.xml -Dhazelcast.rest.enabled=true"```

And have also exposed 5701 port...

> NOTE: I dint know about any mail group for hazelcast problems, so have raised this issue... Any help is appreciated. THANKS

[hazelcast.xml.zip](https://github.com/hazelcast/hazelcast-docker/files/889464/hazelcast.xml.zip)

**Comment by emre-aydin** [comment]
Hi @Shub1427 

How do you start Management Center? You seem to specify `0.0.0.0` as the IP address for Management Center, why is that? If you're starting Management Center by using a docker host, you need to find out the IP address of the docker container of Management Center and specify it in `hazelcast.xml` file. 

If you're starting Management Center on your host and cluster members on Docker containers, you need to use a bridged network and use the gateway adddress in your `hazelcast.xml` file, similar to what is described in this thread: https://forums.docker.com/t/accessing-host-machine-from-within-docker-container/14248/5

BTW, the address for the mail group: https://groups.google.com/forum/#!forum/hazelcast

**Comment by mesutcelik** [comment]
@Shub1427 any update on that?

**Comment by Shub1427** [comment]
I think it used to work... I have not worked on this issue for a long time, though the final compose file for my Docker setup can be found https://github.com/Shub1427/docker-local.

I think `- link` solved the issue...

**Comment by emre-aydin** [comment]
@Shub1427 glad to hear your problem is resolved.
