### ISSUE TITLE
latest tag points to 3.6.4 but not 3.8.1

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast-docker#28]

**Comment by mesutcelik** [comment]
`latest` is a dynamic tag which is updated in every release so you have to pull first before running the image all the time. Otherwise, your local latest image will be launched like 3.6.4 in your case.

Can you please run this two commands and paste the output here?

```
docker pull  hazelcast/hazelcast
docker run -it hazelcast/hazelcast
```

**Comment by gAmUssA** [comment]
it's interesting. looks like it pointed to 3.6.4 in local env.
