### ISSUE TITLE
Remove `MaxGCPauseMillis=5` from Java options 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast-docker#323]
`MaxGCPauseMillis=5` was intended to be used with Java 15 and newer versions. (Discussion here:  #197)  The current release includes Java 11.  Also, some customers take these parameters and use it with other Java versions. 

I suggest removing this option to be on the safe side and let users do fine tuning GC parameters.

**Comment by sertugkaya** [comment]
SF case id 9638
