### ISSUE TITLE
Start releasing updates of the image

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hazelcast-docker#327]
Currently, we release docker image once when we release Hazelcast core.

This means that after some time the JDK gets outdated (#195), there might be newly identified vulnerabilities.

We should release new version of the image more regularly (every week?)

This will only update the base system, not hazelcast itself (for that there is the normal release process).

We need to document that the image may change over time and what the changes are.

**Comment by rvaidya** [comment]
I'd like to add that this is for more than just security updates - user code deployment will stop working if the client applications are updated past the Java version of this image.

**Comment by frant-hartm** [comment]
Currently, we use JDK 11. In the proposed updates we won't update automatically to newer JDK, only newer patch version of the same JDK major version.

Using user code deployment from client app running on JDK 17 to server running on JDK 11 should work if your app uses compile target 11.

If you need a Docker image with JDK 17 you can update the Dockerfile and follow the guide https://github.com/hazelcast/hazelcast-docker#building-your-hazelcast-image

**Comment by ldziedziul** [comment]
Done within https://github.com/hazelcast/hazelcast-docker/pull/576
