### ISSUE TITLE
mancenter docker image is not running

### ISSUE THREAD

**Issue by akrv** [hazelcast/hazelcast-docker#38]
when I put the command, it runs 
`docker run -ti -p 8080:8080 hazelcast/management-center:latest`

and throws this error
```
########################################
# RUN_JAVA=
# JAVA_OPTS=
# starting now....
########################################
Error: Unable to access jarfile mancenter-.war
```

this env var in the docker file is not used in the .sh file 
`ENV HZ_VERSION 3.8.2`

also java and java_opts are not printed out.

**Comment by emre-aydin** [comment]
Hi @akrv,

Thanks for reporting your problem. We had some problems with Management Center docker image creation lately, but I believe they are fixed now. Following commands both work correctly at the moment:

```
docker run -ti -p 8080:8080 hazelcast/management-center:latest
docker run -ti -p 8080:8080 hazelcast/management-center:3.8.2
```

I'm closing the issue now. Feel free to re-open it if your problem is not solved.
