### ISSUE TITLE
ip man center not visible

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast-docker#4]
When I execute the following 2 commands to start management center:
```
docker pull hazelcast/management-center:latest
docker run -ti -p 8080:8080 hazelcast/management-center:latest
```

It isn't clear to me at which ip address I can access management center. The documentation refers to 'hen open from browser MACHINE_IP:8080/mancenter', but what is the MACHINE_IP 

When I use localhost:8080/mancenter, it works fine btw.

So probably it is best to print the ip address when the management center starts?

**Comment by kobalski** [comment]
Updated docs with IP address definitions. See : https://hub.docker.com/r/hazelcast/management-center/
