### ISSUE TITLE
Dockerfile should explicitly specify base image version

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-docker#40]
Relying on the LATEST tag make the build non-repeatable. This was already fixed for the [ManCentre](https://github.com/hazelcast/management-center-docker/commit/c947c134b18c96484320bf50e2715c9809abeee0#diff-3254677a7917c6c01f55212f86c57fbf)

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast-docker/pull/48
