### ISSUE TITLE
Consider using graceful shutdown instead of terminate on SIGTERM

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-docker#42]
Hazelcast registers a shutdown hook which is executed when JVM is about to shutdown. 
By default the hook is calling terminate, but it Docker environment it makes more sense to use a graceful shutdown. 

There a [group property](https://github.com/jerrinot/hazelcast/blob/b9cdf2c705a20a74639536661ebdd0db154078ca/hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java#L353) for this. 

Also see https://docs.docker.com/engine/reference/commandline/stop/
Related to https://github.com/hazelcast/hazelcast-docker/issues/16

**Comment by mesutcelik** [comment]
Apparently, we have to switch on `hazelcast.shutdownhook.policy=GRACEFUL` in every start script if we want to introduce graceful shutdown hook. However, I don't know consequences of this behavior like slowness in scale-in situations. 

`JAVA_OPTS` can be used in based image so need to change the behavior but not sure about k8s and openshift env. @googlielmo WDYT?

**Comment by googlielmo** [comment]
I think we can keep the default behaviour, but I would add instructions in the documentation to show how to change that. I will open a PR for that if that's okay @jerrinot @mesutcelik

**Comment by mesutcelik** [comment]
👍

**Comment by ps-jay** [comment]
Hey @googlielmo ... Did you open that PR?  I can't find it.

**Comment by ps-jay** [comment]
Now documented in README.md here: https://github.com/hazelcast/hazelcast-docker#stopping-a-hazelcast-member

Probably can close this issue.

**Comment by leszko** [comment]
@jerrinot , are you fine to close the issue when it's documented in README how to gracefully shutdown?

**Comment by jerrinot** [comment]
I am ok to have it just documented, but I'd like to see some guidance/considerations. 

Something along these lines: "TERMINATE means a container will be destroyed quickly, but it relies on backup for data safety. GRACEFUL shutdown will first trigger partition migration - which may take some time depending on your data size - and only then it quits. "  +perhaps a link Hazelcast Reference manual.

wdyt?

**Comment by leszko** [comment]
👍 

Let's document it and then close this issue :)
