### ISSUE TITLE
HAZELCAST_CP_MOUNT parameter

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-docker#44]
The usage of $HAZELCAST_CP_MOUNT is not clear in start.sh. We already have HZ_DATA which is used for custom configuration. 

I think we can have only one external mount point like `$HAZELCAST_CP_MOUNT` and put all jars and hazelcast.xml in it. They will automatically be part of classpath..

The same needs to be checked in **hazelcast-enterprise-kubernetes**.

**Comment by leszko** [comment]
I think it's not valid anymore. Closing. @mesutcelik , feel free to reopen if needed.
