### ISSUE TITLE
CLASSPATH usage is misleading

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-docker#45]
see [line](https://github.com/hazelcast/hazelcast-docker/blob/v3.9.1/hazelcast-oss/server.sh#L27) below
`export CLASSPATH=$HAZELCAST_HOME/hazelcast-all-$HZ_VERSION.jar:$CLASSPATH/*`

`CLASSPATH` is considered as a folder which is not true all the time. `:` separated values can be classpath variable as well. 

`export CLASSPATH=$EXT_CP_DIR/*:$EXT_CP_DIR:$HAZELCAST_HOME/hazelcast-all-$HZ_VERSION.jar` that is a good solution` could be better option. 

`$EXT_CP_DIR/*` --> for jar files

`$EXT_CP_DIR` --> for hazelcast.xml ( we can also try to detect hazelcast.xml and pass it via hazelcast.config instead of adding one more EXT_CP_DIR)

**Comment by leszko** [comment]
I think it's not valid anymore. `CLASSPATH` has already been changed in Dockerfiles. Closing. Feel free to reopen if needed.
