### ISSUE TITLE
Java 11 still being used

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-docker#459]
`hazelcast/hazelcast-enterprise:5.2-BETA-1` and `hazelcast/hazelcast:5.2-BETA-1` use Java 11.

A user with the latest LTS java (17) cannot submit Jet jobs with custom classes, executables, etc.

Gives
```
 has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by Kambaa** [comment]
Hello, i'm having the same issue on serialization. It could be nice to have a configurative JDK option for the docker builds. We can select the JDK / JRE version of the Hazelcast Image. 
Thank you.

**Comment by ldziedziul** [comment]
Fixed by https://github.com/hazelcast/hazelcast-docker/pull/694
