### ISSUE TITLE
Add Jcache to classpath

### ISSUE THREAD

**Issue by fsamir** [hazelcast/hazelcast-docker#50]
Hi,

I am running hazelcast/hazelcast:3.8.8 and I get the following error when I try to connect to it using Jcache Client:
`Service with name 'hz:impl:cacheService' not found`

**Comment by hasancelik** [comment]
Hi @fsamir,

Could you give more information your setup? It would be great, if you send logs, server-client xml as well.

**Comment by hasancelik** [comment]
Hi @fsamir again,

I have talked with my colleagues, it seems problem you have encountered is known issue. We will fix this issue ASAP. 

Thanks for your report.

**Comment by fsamir** [comment]
Hi @hasancelik ,

I ended up solving my issue. It turns out that in my specific case, adding jache.jar to the classpath is not enough because I also need to include other jars, with the `Serializable` classes I intent to store in the case.

However, adding jcache.jar would still be useful to someone willing to store only primitive types.

I am using Hazelcast as a back-end for Bucket4j, hence I had to add bucket4j jars to the classpath, as well. Something like this:

```
cd /opt/hazelcast/lib
wget http://central.maven.org/maven2/javax/cache/cache-api/1.1.0/cache-api-1.1.0.jar
wget http://central.maven.org/maven2/com/github/vladimir-bukhtoyarov/bucket4j-core/3.0.2/bucket4j-core-3.0.2.jar
wget http://central.maven.org/maven2/com/github/vladimir-bukhtoyarov/bucket4j-core/3.0.2/bucket4j-core-3.0.2.jar
wget http://central.maven.org/maven2/com/github/vladimir-bukhtoyarov/bucket4j-jcache/3.0.2/bucket4j-jcache-3.0.2.jar
wget http://central.maven.org/maven2/com/github/vladimir-bukhtoyarov/bucket4j-hazelcast/3.0.2/bucket4j-hazelcast-3.0.2.jar

docker run --name my-hazelcast-rate-limit -d -p 5701:5701 -e CLASSPATH="/opt/hazelcast/lib/" -e JAVA_OPTS="-Dhazelcast.config=/opt/hazelcast/conf/hazelcast.xml -Dhazelcast.ip=`ip route get 8.8.8.8 | awk '{print $NF; exit}'` -Dhazelcast.port=5701" -v /opt/hazelcast/lib/:/opt/hazelcast/lib/ -v /opt/hazelcast/conf/:/opt/hazelcast/conf/ -ti hazelcast/hazelcast:3.8.8
```

I will wrap it up in a new Docker image and notify the Bucket4j guys, in case they want to use it in their demo projects.

Thanks

**Comment by hasancelik** [comment]
Thanks for the update and workaround @fsamir 👍 

> However, adding jcache.jar would still be useful to someone willing to store only primitive types.

I have sent PR for master branch, after this PR is merged `latest` tag will have the fix. --> https://github.com/hazelcast/hazelcast-docker/pull/51

**Comment by fsamir** [comment]
@hasancelik 
thanks. 
As I mentioned earlier, I've done the same with the addition of Bucket4j jars, as well.

https://github.com/fsamir/hazelcast-bucket4j
https://hub.docker.com/r/fsamir/hazelcast-bucket4j/

**Comment by hasancelik** [comment]
@fsamir 

>I've done the same with the addition of Bucket4j jars, as well, in case someone is after a quick way to play with bucket4j.
https://github.com/fsamir/hazelcast-bucket4j
https://hub.docker.com/r/fsamir/hazelcast-bucket4j/

Thanks for the `hazelcast-bucket4j` image. 👍 

>As a side note, It is worth mentioning I struggled to find out I was also supposed to include the Bucket4 jars (or any jar with the classes you wish to Serialize in the cache) to the Hazelcast server. Mostly because of misleading error messages.
When Jcache.jar as missing, the client received a clear error message stating: Server side: JCache not found in classpath.
However, when the Serializable classes were missing, there was no mention to Server side in the error message, only SerializableException. Thus, I spent a lot of time trying to debug the client side for a potential Classloader problem.
It would be worth to add Server side to the Serialization errors, as well.

I will talk about `misleading error messages` with colleagues who is working on hazelcast server side serializability. Thanks for pointing out.

**Comment by erentuncer** [comment]
> @fsamir
> 
> > I've done the same with the addition of Bucket4j jars, as well, in case someone is after a quick way to play with bucket4j.
> > https://github.com/fsamir/hazelcast-bucket4j
> > https://hub.docker.com/r/fsamir/hazelcast-bucket4j/
> 
> Thanks for the `hazelcast-bucket4j` image. 👍
> 
> > As a side note, It is worth mentioning I struggled to find out I was also supposed to include the Bucket4 jars (or any jar with the classes you wish to Serialize in the cache) to the Hazelcast server. Mostly because of misleading error messages.
> > When Jcache.jar as missing, the client received a clear error message stating: Server side: JCache not found in classpath.
> > However, when the Serializable classes were missing, there was no mention to Server side in the error message, only SerializableException. Thus, I spent a lot of time trying to debug the client side for a potential Classloader problem.
> > It would be worth to add Server side to the Serialization errors, as well.
> 
> I will talk about `misleading error messages` with colleagues who is working on hazelcast server side serializability. Thanks for pointing out.

Hi Hasan,

Apparently, I spent lots of time because of misleading error messages too as @fsamir mentioned in this thread. 
I'm using hazelcast-client to connect Hazelcast server from a basic SpringBoot application. I'm %100 sure that cache-api.jar is on the classpath of the application. But I got same error too.

```
com.hazelcast.spi.exception.ServiceNotFoundException: Service with name 'hz:impl:cacheService' not found!
	at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:367) ~[hazelcast-3.12.6.jar:3.12.6]
```

Although it cost me 1 week at least I have now understand that we should provide the cache-api on classpath at Hazelcast Server side. But I wanted to remind that those error messages are very important to figure out about the stuff -as you know- 
Just a friendly reminder; please consider again to refactor misleading messages. If needed may be we should follow it with a new issue ticket.

Thanks.
