### ISSUE TITLE
Wrong bind request from [172.20.215.37]:5701! This node is not the requested endpoint: [10.68.144.200]:5701

### ISSUE THREAD

**Issue by XieXianbin** [hazelcast/hazelcast-docker#54]
[root@cicd-cmp2-k8s-01 ~]# kubectl get service
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP                           PORT(S)                         AGE
hazelcast                   NodePort    10.68.144.200   <none>                                5701:29634/TCP                  55s
[root@cicd-cmp2-k8s-01 ~]# kubectl get pods
NAME                                         READY     STATUS    RESTARTS   AGE
hazelcast-55fsv                              1/1       Running   0          26m
hazelcast-8cjr9                              1/1       Running   0          26m
hazelcast-jk9w2                              1/1       Running   0          26m
[root@cicd-cmp2-k8s-01 ~]# kubectl logs hazelcast-55fsv
Kubernetes Namespace: default
Kubernetes Service DNS: hazelcast
########################################
# RUN_JAVA=
# JAVA_OPTS=
# CLASSPATH=/*:/opt/hazelcast/*:/opt/hazelcast/external/*:
########################################
Checking custom configuration
no custom configuration found
Jan 16, 2018 1:21:30 AM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast.xml' from working directory.
Jan 16, 2018 1:21:31 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.9.2] Prefer IPv4 stack is true.
Jan 16, 2018 1:21:31 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.9.2] Picked [172.20.28.160]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
Jan 16, 2018 1:21:31 AM com.hazelcast.system
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Hazelcast 3.9.2 (20180103 - 17e4ec3) starting at [172.20.28.160]:5701
Jan 16, 2018 1:21:31 AM com.hazelcast.system
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Copyright (c) 2008-2017, Hazelcast, Inc. All Rights Reserved.
Jan 16, 2018 1:21:31 AM com.hazelcast.system
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Configured Hazelcast Serialization version: 1
Jan 16, 2018 1:21:31 AM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Backpressure is disabled
Jan 16, 2018 1:21:31 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Kubernetes Discovery properties: { service-dns: hazelcast, service-dns-timeout: 5, service-name: null, service-label: null, service-label-value: true, namespace: default, resolve-not-ready-addresses: false, kubernetes-master: https://kubernetes.default.svc}
Jan 16, 2018 1:21:31 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Kubernetes Discovery activated resolver: DnsEndpointResolver
Jan 16, 2018 1:21:32 AM com.hazelcast.instance.Node
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Activating Discovery SPI Joiner
Jan 16, 2018 1:21:32 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Starting 16 partition threads and 9 generic threads (1 dedicated for priority tasks)
Jan 16, 2018 1:21:32 AM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Jan 16, 2018 1:21:32 AM com.hazelcast.core.LifecycleService
INFO: [172.20.28.160]:5701 [dev] [3.9.2] [172.20.28.160]:5701 is STARTING
Jan 16, 2018 1:21:32 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connecting to /10.68.144.200:5701, timeout: 0, bind-any: true
Jan 16, 2018 1:21:32 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Established socket connection between /172.20.28.160:59385 and /10.68.144.200:5701
Jan 16, 2018 1:21:33 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connection[id=1, /172.20.28.160:59385->/10.68.144.200:5701, endpoint=[10.68.144.200]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
Jan 16, 2018 1:21:33 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connecting to /10.68.144.200:5701, timeout: 0, bind-any: true
Jan 16, 2018 1:21:33 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Established socket connection between /172.20.28.160:48719 and /10.68.144.200:5701
Jan 16, 2018 1:21:33 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connection[id=2, /172.20.28.160:48719->/10.68.144.200:5701, endpoint=[10.68.144.200]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
Jan 16, 2018 1:21:34 AM com.hazelcast.nio.tcp.TcpIpAcceptor
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Accepting socket connection from /172.20.215.37:55949
Jan 16, 2018 1:21:34 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Established socket connection between /172.20.28.160:5701 and /172.20.215.37:55949
Jan 16, 2018 1:21:34 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
WARNING: [172.20.28.160]:5701 [dev] [3.9.2] Wrong bind request from [172.20.215.37]:5701! This node is not the requested endpoint: [10.68.144.200]:5701
Jan 16, 2018 1:21:34 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connection[id=3, /172.20.28.160:5701->/172.20.215.37:55949, endpoint=null, alive=false, type=MEMBER] closed. Reason: Wrong bind request from [172.20.215.37]:5701! This node is not the requested endpoint: [10.68.144.200]:5701
Jan 16, 2018 1:21:34 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connecting to /10.68.144.200:5701, timeout: 0, bind-any: true
Jan 16, 2018 1:21:34 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Established socket connection between /172.20.28.160:57914 and /10.68.144.200:5701
Jan 16, 2018 1:21:34 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connection[id=4, /172.20.28.160:57914->/10.68.144.200:5701, endpoint=[10.68.144.200]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
Jan 16, 2018 1:21:35 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connecting to /10.68.144.200:5701, timeout: 0, bind-any: true
Jan 16, 2018 1:21:35 AM com.hazelcast.nio.tcp.TcpIpAcceptor
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Accepting socket connection from /10.3.32.211:51823
Jan 16, 2018 1:21:35 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Established socket connection between /172.20.28.160:5701 and /10.3.32.211:51823
Jan 16, 2018 1:21:35 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Established socket connection between /172.20.28.160:51823 and /10.68.144.200:5701
Jan 16, 2018 1:21:35 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
WARNING: [172.20.28.160]:5701 [dev] [3.9.2] Wrong bind request from [172.20.28.160]:5701! This node is not the requested endpoint: [10.68.144.200]:5701
Jan 16, 2018 1:21:35 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connection[id=5, /172.20.28.160:5701->/10.3.32.211:51823, endpoint=null, alive=false, type=MEMBER] closed. Reason: Wrong bind request from [172.20.28.160]:5701! This node is not the requested endpoint: [10.68.144.200]:5701
Jan 16, 2018 1:21:35 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connection[id=6, /172.20.28.160:51823->/10.68.144.200:5701, endpoint=[10.68.144.200]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
Jan 16, 2018 1:21:36 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connecting to /10.68.144.200:5701, timeout: 0, bind-any: true
Jan 16, 2018 1:21:36 AM com.hazelcast.nio.tcp.TcpIpAcceptor
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Accepting socket connection from /10.3.32.211:37234
Jan 16, 2018 1:21:36 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Established socket connection between /172.20.28.160:37234 and /10.68.144.200:5701
Jan 16, 2018 1:21:36 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Established socket connection between /172.20.28.160:5701 and /10.3.32.211:37234
Jan 16, 2018 1:21:36 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
WARNING: [172.20.28.160]:5701 [dev] [3.9.2] Wrong bind request from [172.20.28.160]:5701! This node is not the requested endpoint: [10.68.144.200]:5701
Jan 16, 2018 1:21:36 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connection[id=8, /172.20.28.160:5701->/10.3.32.211:37234, endpoint=null, alive=false, type=MEMBER] closed. Reason: Wrong bind request from [172.20.28.160]:5701! This node is not the requested endpoint: [10.68.144.200]:5701
Jan 16, 2018 1:21:36 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connection[id=7, /172.20.28.160:37234->/10.68.144.200:5701, endpoint=[10.68.144.200]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
Jan 16, 2018 1:21:37 AM com.hazelcast.nio.tcp.TcpIpAcceptor
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Accepting socket connection from /172.20.215.37:52217
Jan 16, 2018 1:21:37 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Established socket connection between /172.20.28.160:5701 and /172.20.215.37:52217
Jan 16, 2018 1:21:37 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
WARNING: [172.20.28.160]:5701 [dev] [3.9.2] Wrong bind request from [172.20.215.37]:5701! This node is not the requested endpoint: [10.68.144.200]:5701
Jan 16, 2018 1:21:37 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Connection[id=9, /172.20.28.160:5701->/172.20.215.37:52217, endpoint=null, alive=false, type=MEMBER] closed. Reason: Wrong bind request from [172.20.215.37]:5701! This node is not the requested endpoint: [10.68.144.200]:5701
Jan 16, 2018 1:21:37 AM com.hazelcast.system
INFO: [172.20.28.160]:5701 [dev] [3.9.2] Cluster version set to 3.9
Jan 16, 2018 1:21:37 AM com.hazelcast.internal.cluster.ClusterService
INFO: [172.20.28.160]:5701 [dev] [3.9.2] 

Members {size:1, ver:1} [
	Member [172.20.28.160]:5701 - 6f5267d6-250f-4b46-834d-2e54ff3cbada this
]

Jan 16, 2018 1:21:37 AM com.hazelcast.core.LifecycleService
INFO: [172.20.28.160]:5701 [dev] [3.9.2] [172.20.28.160]:5701 is STARTED
^C[root@cicd-cmp2-k8s-01 ~]#

**Comment by hasancelik** [comment]
Hi @XieXianbin ,

Could you send `hazelcast.xml` config file?

Thanks.

**Comment by googlielmo** [comment]
Hi @XieXianbin ,

What version of Hazelcast Kubernetes image are you using exactly (full name and tag)?
Also, the output from `kubectl version` would be helpful.

**Comment by XieXianbin** [comment]
[root@cicd-cmp2-k8s-01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[root@cicd-cmp2-k8s-01 ~]# docker images | grep cast
hazelcast/hazelcast-kubernetes                             3.9.2               584c876ff83b        12 days ago         443MB
[root@cicd-cmp2-k8s-01 ~]#

**Comment by googlielmo** [comment]
Hi @XieXianbin 

Could you please retry using  `HAZELCAST_KUBERNETES_NAMESPACE` and `HAZELCAST_KUBERNETES_SERVICE_NAME` in `hz-config.yaml` (instead of `HAZELCAST_KUBERNETES_SERVICE_DNS`) ?

If that works, it may be an issue related to DNS discovery that we would have to investigate.

**Comment by XieXianbin** [comment]
Tks, use the rest api mode is support.
