### ISSUE TITLE
3.8.9 Kubernetes Docker file points to 3.9.1

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-docker#55]
https://github.com/hazelcast/hazelcast-docker/blob/v3.8.9/hazelcast-enterprise-kubernetes/Dockerfile#L12
https://github.com/hazelcast/hazelcast-docker/blob/v3.8.9/hazelcast-kubernetes/Dockerfile#L12

@hasancelik 
Can you please check?

**Comment by mesutcelik** [comment]
@hasancelik were you able to check that?

**Comment by hasancelik** [comment]
This issue was solved in current version of release script so closing it.
