### ISSUE TITLE
Add sanity checks for automatic rebuilding docker images

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast-docker#581]
We should add some checks in https://github.com/hazelcast/hazelcast-docker/blob/master/.github/workflows/check-base-images.yml workflow to be sure that new image can be started by our users.

Currently for standard release it is checked manually by QE members.

**Comment by ldziedziul** [comment]
we can reuse what we have in PR builder
https://github.com/hazelcast/hazelcast-docker/blob/master/.github/workflows/build-pr.yml#L35
