### ISSUE TITLE
Broken links in Maven Central artifacts

### ISSUE THREAD

**Issue by nishaatr** [hazelcast/hazelcast-docker#602]
Example https://central.sonatype.com/artifact/com.hazelcast/hazelcast/5.3.1

![image](https://github.com/hazelcast/hazelcast-docker/assets/12186256/f99404ea-0eee-4f8d-a81a-2577a02fe94d)

![image](https://github.com/hazelcast/hazelcast-docker/assets/12186256/74e73400-6e5a-4e0a-a045-06bcec18a9bf)

![image](https://github.com/hazelcast/hazelcast-docker/assets/12186256/f6a82fd9-5316-4270-b864-5cc2efb9a591)

I see same thing with other releases as well

**Comment by ldziedziul** [comment]
Not related to this project
