### ISSUE TITLE
Why have `server.sh` and `stop.sh` at all?

### ISSUE THREAD

**Issue by ps-jay** [hazelcast/hazelcast-docker#62]
Hi folks,

I'm wondering why there is `server.sh` and `stop.sh` in the containers?

Why not just run the `java -server ...` command in the foreground?

**Comment by w0203j** [comment]
Yes I was wondering the same thing.

**Comment by mesutcelik** [comment]
👍 

I think those can be removed with a proper documentation update. Before removing them, we need to move env variable definitions in the server.sh to Docker file and update documentation accordingly. Those need to be done in all Dockerfiles...

We would appreciate any contribution!

**Comment by ps-jay** [comment]
Guess this is sort of related to #16, and maybe #42 as well.

I'll have a think on how to approach this.

**Comment by ps-jay** [comment]
Closed via #66
