### ISSUE TITLE
Enterprise Docker Image's `LABEL` refers to `IMDG`

### ISSUE THREAD

**Issue by JackPGreen** [hazelcast/hazelcast-docker#742]
The `LABEL` metadata on the EE image refers to `IMDG` - I think that's outdated and should be removed.

The OS image has no such `LABEL` metadata

https://github.com/hazelcast/hazelcast-docker/blob/5793b2e509741c20ab93ac8c0697d1d33e989bf8/hazelcast-enterprise/Dockerfile#L26

I'm unsure where this is actually displayed - I can't see it on [Docker Hub](https://hub.docker.com/r/hazelcast/hazelcast-enterprise).

For reference, was added in https://github.com/hazelcast/hazelcast-docker/pull/177

**Comment by ldziedziul** [comment]
It's something required by OpenShift, at least at some point in time https://github.com/hazelcast/hazelcast-docker/pull/177#discussion_r544912212

We should update the name either way. 

BTW You can check it locally:
```shelll
docker inspect --format='{{json .Config.Labels}}' hazelcast/hazelcast-enterprise:5.4.0 | jq
```
