### ISSUE TITLE
Consolidate script test elements

### ISSUE THREAD

**Issue by JackPGreen** [hazelcast/hazelcast-docker#749]
You know as well as I do the future never comes ;)

I think best do it now as its quite a bit of duplication.  If its time consuming then may be add a TODO comment and resolve this issue. Not too fussed. Only trying to reduce dups and future maintenance overhead (albeit small)

_Originally posted by @nishaatr in https://github.com/hazelcast/hazelcast-docker/pull/747#discussion_r1601534099_

**Comment by JackPGreen** [comment]
I'm not sure this is possible.

The boilerplate code is a function used to determine the `SCRIPT_DIR`, respecting symlinks etc.

Any centralised code would end up in the `SCRIPT_DIR`, which you'd still need to resolve - so you can't really get away from it.

I'm not sure we need to follow symlinks in this scenario, but I was unable to ascertain any further [beyond when it was added](https://github.com/hazelcast/hazelcast-docker/pull/554).

**Comment by nishaatr** [comment]
understood. thanks
