### ISSUE TITLE
REST inteface does not seem to work

### ISSUE THREAD

**Issue by tornstam** [hazelcast/hazelcast-docker#8]
curl -vvv "http://192.168.99.100:5701/hazelcast/rest/cluster"
*   Trying 192.168.99.100...
* Connected to 192.168.99.100 (192.168.99.100) port 5701 (#0)
> GET /hazelcast/rest/cluster HTTP/1.1
> Host: 192.168.99.100:5701
> User-Agent: curl/7.43.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 192.168.99.100 left intact
curl: (52) Empty reply from server

Hazelcast logs
hazelcast | INFO: [172.17.0.5]:5701 [dev] [3.6.2] Established socket connection between /172.17.0.5:5701 and /192.168.99.1:55400
hazelcast | May 10, 2016 7:30:25 AM com.hazelcast.nio.tcp.TcpIpConnection
hazelcast | INFO: [172.17.0.5]:5701 [dev] [3.6.2] Connection [/192.168.99.1:55400] lost. Reason: Socket explicitly closed

**Comment by mesutcelik** [comment]
REST is disabled by default. Can you try this?
`docker run -ti --net=host -e JAVA_OPTS="-Dhazelcast.rest.enabled=true" hazelcast/hazelcast`

**Comment by tornstam** [comment]
Not much about that in the documentation tough. Can't find it even now when I know what to look for.

**Comment by mesutcelik** [comment]
You might be looking into wrong documentation.

http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#checking-the-status-of-the-cluster-for-rest-client

```NOTE: REST client request listener service is not enabled by default. You should enable it on your cluster members to use REST client. It can be enabled using the system property hazelcast.rest.enabled```

**Comment by tornstam** [comment]
Yep, you're right I was just googleing for it.
