### ISSUE TITLE
hazelcast (3.7.8) not able to connect to mancenter

### ISSUE THREAD

**Issue by dhruv-bansal** [hazelcast/hazelcast-docker#85]
I am working on hazelcast version 3.7.8
Ran the docker image for mancenter 
`docker run -p 8080:8080 hazelcast/management-center:3.7.8`
Ran the docker image for hazelcast (specifying the mancenter URL) 
`docker run -e MANCENTER_URL="http://localhost:8080/mancenter" hazelcast/hazelcast:3.7.8`

hazelcast server is not able to connect mancenter

<img width="1659" alt="screen shot 2018-07-21 at 12 18 23 am" src="https://user-images.githubusercontent.com/11644608/43019752-a24fd154-8c7b-11e8-88e3-cf451a3ae44b.png">

**Comment by mesutcelik** [comment]
Hi @dhruv-bansal ,
Setting `MANCENTER_URL` has been added in the latest hazelcast docker image. Can you please try to use hazelcast `3.10.x` docker image. You have to use latest MC 3.10.x docker image too to make it all working.

**Comment by dhruv-bansal** [comment]
I have tried with the latest version also, still, I am not able to get man center up and running
docker run  -e MANCENTER_URL="http://localhost:8080/mancenter" -p 5701:5701 hazelcast/hazelcast

**Comment by dhruv-bansal** [comment]
using hazelcast without docker has mancenter feature in community version also, so why this feature is not provided in docker file. I see it is only available in enterprise version

**Comment by mesutcelik** [comment]
Management Center has its own docker image. 
https://github.com/hazelcast/management-center-docker
You can still run Management Center without license key if you connect up to 2 member hazelcast cluster.

I am closing this ticket. please feel free to ask your questions to communication channels listed on https://hazelcast.org/get-involved/

**Comment by leszko** [comment]
@mesutcelik , I think what @dhruv-bansal meant is that in the Hazelcast Enterprise Docker Image we template `hazelcast.xml` with Management Center and expose it in the env variable [1], but we don't do it for the OSS Docker Image [2]. 

In general, I agree that we should be consistent, but not sure it's better to template both or remove templating from both. The drawback of having a template is that, if you override `hazelcast.xml` with your own configuration, you may forget that your variable will no longer work. On the good side, is that you don't need to create your own configuration if you just want to play with Management Center, the variable is enough.

What do you guys think?

[1] https://github.com/hazelcast/hazelcast-docker/blob/master/hazelcast-enterprise/hazelcast.xml
[2] https://github.com/hazelcast/hazelcast-docker/tree/master/hazelcast-oss

**Comment by dhruv-bansal** [comment]
@leszko Thanks for explaining my intention. I mean exactly what you re-iterated. As a developer management center is the quick reference point for various things happening in Hazelcast. Overriding hazelcast.xml as I understood till now is not as straightforward as running the docker image by just manipulating its environment variable. So, IMO environment variable support for mancenter is a must.

**Comment by leszko** [comment]
I'm re-opening the issue. Let's add it.

@mesutcelik , please shout if we should not template Mancenter for Hazelcast OSS.

**Comment by mesutcelik** [comment]
What I think to be consistent is that ENV Variable support must be available for both and we should pass the value to hazelcast member process via System Property. This property should override whatever available in the hazelcast config. 

Having said that, I am not sure we have a supporting system property for mancenter url while starting hazelcast member... @emre-aydin ?

**Comment by emre-aydin** [comment]
@mesutcelik  I don't know of any such parameter. Did a quick check in the documentation and couldn't find one, so I'm assuming there are none.
