### ISSUE TITLE
-Xmx parameter isn't set properly for MAX_HEAP_SIZE env

### ISSUE THREAD

**Issue by sitnik** [hazelcast/hazelcast-docker#89]
https://github.com/hazelcast/hazelcast-docker/blob/43add84d04101108452e78696081d2f9b8e0cb5f/hazelcast-oss/Dockerfile#L71

This line should end with -Xmx${MAX_HEAP_SIZE}
Now you set -Xms twice.

**Comment by mesutcelik** [comment]
Dropping support for `MAX_HEAP_SIZE` and `MIN_HEAP_SIZE` could be a better option. They can already be passed along with other params with `JAVA_OPTS`

**Comment by leszko** [comment]
@sitnik , Good Spot, thanks!

@mesutcelik I totally agree, the question is if we want to be backwards compatible with the new Docker image. Wdyt?

**Comment by sitnik** [comment]
In my case I do use MAX_HEAP_SIZE and MIN_HEAP_SIZE in Kubernetes Helm chart for our application:
https://github.com/devicehive/devicehive-docker/blob/master/k8s/devicehive/templates/dh-hazelcast-deployment.yaml#L22 and would like to save it. I was testing our application scaling (and also a Hazelcast pod) in Kubernetes after you added k8s discovery plugin in the main image, and found this issue. 

I think fixing issue and maintaining backward compatibility at this point is very easy, just one typo.

**Comment by leszko** [comment]
@sitnik you're right. I've fixed the typos, so the `latest` image should be build in few minutes. Thanks!
