### ISSUE TITLE
Smaller image size?

### ISSUE THREAD

**Issue by eduardolundgren** [hazelcast/hazelcast-docker#9]
The current image size of the `oss` version is `259 MB`, it's unacceptable to keep the current size just because a not-well optimized base image, that's mostly because it's using `java:7`.

**Comment by mesutcelik** [comment]
Hi @eduardolundgren ,
Thanks for the heads up!

We switched to jre in 3.6.3+ so you can check if that is ok.
https://hub.docker.com/r/hazelcast/hazelcast/tags/

I am closing the issue but feel free to reopen if you still see a problem...

**Comment by eduardolundgren** [comment]
Looks a lot better, although it can be reduced even more by using a Alpine based JRE image, e.g.

https://gist.github.com/eduardolundgren/dea03228ad6ee5403b35364b4ab846de

![](https://cloud.githubusercontent.com/assets/3574444/15964703/2c4f5050-2ef0-11e6-8858-bc165e403137.png)

Thank you!
