### ISSUE TITLE
Update java version to >10

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast-docker#96]
With the release of Java 10 the JVM now recognizes constraintst(memory,cpu) set by container control groups.

For more details see: https://blog.docker.com/2018/04/improved-docker-container-integration-with-java-10/

**Comment by leszko** [comment]
In general I think it's a good idea. The drawback is that there is no `10-alpine` image available. We could go straight to `12-alpine`. I checked and the size of our `hazelcast/hazelcast` would change from `90MB` to `231MB`, which is a lot. On the other hand, we'll need to move from Java 8 someday...

@eminn @jerrinot @mesutcelik what are your thoughts? 

We can:
- Change to `12-alpine` and don't think about the size
- Wait, maybe they'll create some reduced size JRE

**Comment by leszko** [comment]
One more comment to this issue: if we plan to include OpenSSL in `hazelcast/hazelcast-enterprise`, we need to update to `12-alpine`, since OpenSSL does not work currectly with Alpine 8.

**Comment by mesutcelik** [comment]
just putting as reference in response to https://github.com/hazelcast/hazelcast-docker/issues/96#issuecomment-446890652
This PR makes it possible to enable OpenSSL with Alpine 8
https://github.com/hazelcast/hazelcast-docker/pull/102

**Comment by jerrinot** [comment]
It would make sense to go to Java 11. But I don't understand the size difference. 231MB vs 90MB is a lot. What's causing it?

**Comment by jerrinot** [comment]
this should be good enough for now: `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap`

it should work on latest OpenJDK 8 builds

**Comment by leszko** [comment]
> It would make sense to go to Java 11. But I don't understand the size difference. 231MB vs 90MB is a lot. What's causing it?

https://stackoverflow.com/questions/53375613/why-is-the-java-11-base-docker-image-so-large-openjdk11-jre-slim



> this should be good enough for now: `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap`
> 
> it should work on latest OpenJDK 8 builds

We can try it, but my only worry is if we should ship experimental features (people run our image on the production environments!). @jerrinot . wdyt?

**Comment by mesutcelik** [comment]
Latest versions of Java 8 comes with Docker Support by default. 

This is the Release Notes of JDK-8u191
https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html#JDK-8146115
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8146115

If you check latest Hazelcast Docker Release as of today, you can see that Java Runtime detects that it is running inside Docker Container, recognizes that Container has 512M limitation, applies MaxRAMFraction to calculate MaxHeapSize as 512/4 which gives 134217728
```
$ docker container run -ti -m 512M hazelcast/hazelcast:3.12.3 bash -c 'java -XX:+PrintFlagsFinal -version | grep -E "MaxHeapSize|MaxRAMFraction"'
    uintx DefaultMaxRAMFraction                     = 4                                   {product}
    uintx MaxHeapSize                              := 134217728                           {product}
    uintx MaxRAMFraction                            = 4                                   {product}
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (IcedTea 3.13.0) (Alpine 8.222.10-r0)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

```

If you check some older version of Hazelcast (3.9), you will see it is using a Java Runtime before 8u191. That means it does not consider Docker Container limitations and  calculates MaxHeapSize based on psychical available memory. 2GB/4 ~= 512M 
```
$ docker container run -ti -m 512M hazelcast/hazelcast:3.9 bash -c 'java -XX:+PrintFlagsFinal -version | grep -E "MaxHeapSize|MaxRAMFraction"'
    uintx DefaultMaxRAMFraction                     = 4                                   {product}
    uintx MaxHeapSize                              := 524288000                           {product}
    uintx MaxRAMFraction                            = 4                                   {product}
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

```

**Comment by leszko** [comment]
Good finding @mesut 👍 

Should we then close this issue? @eminn

**Comment by eminn** [comment]
Thanks for the finding @mesutcelik, I think we can close this for now.
